'use client'
import React from 'react'
import Image from 'next/image'
import CallToAction from '../components/CallToAction'
import whiteDiamond from '../../../public/assets/WhiteDiamond.png'
import pinkdiamond from '../../../public/assets/PinkDiamond.png'

const page = () => {
    return (
        <div className='min-h-screen p-6  text-white'>
            {/* Header Section */}
            <div className='flex items-center gap-2 flex-wrap justify-center mb-8'>
                <Image src={pinkdiamond} alt='' className='w-6 h-6' />
                <div className='font-clash font-[600] text-3xl uppercase'>Terms and Conditions</div>
            </div>

            {/* Subtitle */}
            <div className='font-urbanist font-[600] text-[#969696] max-w-4xl mx-auto text-center mb-12'>
                Feel free to ask any query related to our products and any additional help we will be happy to help you out.
            </div>

            {/* Terms Content */}
            <div className='max-w-6xl mx-auto font-urbanist text-white'>
                <div className='space-y-8'>
                    <div>
                        <h1 className='text-2xl font-bold mb-4'>Terms &amp; Conditions</h1>
                        <p className='mb-4'><strong>Last Updated:</strong> [Insert Date]</p>
                        
                        <div className='space-y-6 text-justify leading-relaxed'>
                            <p>
                                This document is an electronic record in terms of the Information Technology Act, 2000, and rules made thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                            </p>
                            
                            <p>
                                This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name www.festbuzz.in (&quot;Website&quot;), including the related mobile site and mobile application (hereinafter referred to as the &quot;Platform&quot;).
                            </p>
                            
                            <p>
                                The Platform is owned and operated by Maxhilaration Ventures (operating as Festbuzz), a company incorporated under the Companies Act, 1956, with its registered office at New Sojan Road, Mahroni, Lalitpur, Uttar Pradesh 284405, India (hereinafter referred to as &quot;Platform Owner&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;).
                            </p>
                            
                            <p>
                                Your use of the Platform, its services, and tools are governed by the following terms and conditions (&quot;Terms of Use&quot;) along with applicable policies, which are incorporated herein by reference. If you transact on the Platform, you will be subject to the policies applicable to such transactions. By merely using the Platform, you agree to these Terms of Use and such policies, and they constitute your binding obligations with the Platform Owner.
                            </p>
                            
                            <p className='font-bold uppercase'>
                                ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE. PLEASE READ THESE TERMS CAREFULLY BEFORE PROCEEDING.
                            </p>
                        </div>
                    </div>

                    {/* Section 1 */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#E1FF01]'>1. Eligibility &amp; User Obligations</h2>
                        <div className='ml-4 space-y-3'>
                            <p>To access and use the Services, you agree to:</p>
                            <ul className='list-disc ml-6 space-y-2'>
                                <li>Provide true, accurate, and complete information during and after registration.</li>
                                <li>Be responsible for all acts done using your registered account.</li>
                                <li>Ensure compliance with all applicable Indian laws and local regulations while using the Platform.</li>
                            </ul>
                        </div>
                    </div>

                    {/* Section 2 */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#E1FF01]'>2. Use of Services</h2>
                        <div className='ml-4 space-y-3'>
                            <ul className='list-disc ml-6 space-y-3'>
                                <li>Neither we nor third parties provide any warranty or guarantee regarding the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this Platform or through the Services.</li>
                                <li>Such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>
                                <li>Your use of the Platform and Services is entirely at your own risk and discretion. You are required to independently assess and ensure that the Services meet your requirements.</li>
                            </ul>
                        </div>
                    </div>

                    {/* Section 3 */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#E1FF01]'>3. Intellectual Property</h2>
                        <div className='ml-4 space-y-3'>
                            <ul className='list-disc ml-6 space-y-3'>
                                <li>The contents of the Platform and Services are proprietary to us and licensed to us.</li>
                                <li>You have no authority to claim intellectual property rights, title, or interest in the contents, including (but not limited to) design, layout, look, and graphics.</li>
                                <li>Any unauthorized use of the Platform and/or Services may lead to action against you under these Terms of Use and/or applicable laws.</li>
                            </ul>
                        </div>
                    </div>

                    {/* Section 4 */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#E1FF01]'>4. Payments</h2>
                        <div className='ml-4'>
                            <p>You agree to pay all charges associated with availing of the Services on the Platform.</p>
                        </div>
                    </div>

                    {/* Section 5 */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#E1FF01]'>5. Prohibited Uses</h2>
                        <div className='ml-4'>
                            <p>You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, or forbidden under these Terms or under applicable Indian/local laws.</p>
                        </div>
                    </div>

                    {/* Section 6 */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#E1FF01]'>6. Third-Party Links</h2>
                        <div className='ml-4 space-y-3'>
                            <ul className='list-disc ml-6 space-y-3'>
                                <li>The Platform and Services may contain links to third-party websites.</li>
                                <li>On accessing these links, you will be governed by the terms of use, privacy policy, and other applicable policies of such third-party websites.</li>
                                <li>These links are provided for convenience and information purposes only.</li>
                            </ul>
                        </div>
                    </div>

                    {/* Section 7 */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#E1FF01]'>7. Contract Formation</h2>
                        <div className='ml-4'>
                            <p>By initiating a transaction for availing of the Services, you are entering into a legally binding and enforceable contract with the Platform Owner.</p>
                        </div>
                    </div>

                    {/* Section 8 */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#E1FF01]'>8. Indemnity</h2>
                        <div className='ml-4 space-y-3'>
                            <p>You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies, officers, directors, agents, and employees from any claim, demand, or action (including reasonable attorney fees) arising out of:</p>
                            <ul className='list-disc ml-6 space-y-2'>
                                <li>Your breach of these Terms of Use, Privacy Policy, or other applicable policies,</li>
                                <li>Your violation of any law, rules, or regulations, or</li>
                                <li>Your infringement of the rights of a third party (including intellectual property rights).</li>
                            </ul>
                        </div>
                    </div>

                    {/* Section 9 */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#E1FF01]'>9. Limitation of Liability</h2>
                        <div className='ml-4 space-y-3'>
                            <ul className='list-disc ml-6 space-y-3'>
                                <li>In no event will the Platform Owner be liable for any indirect, consequential, incidental, special, or punitive damages including (without limitation) loss of profits, revenues, business interruption, data loss, or business opportunities.</li>
                                <li>Our liability, whether arising in contract, tort, negligence, warranty, or otherwise, shall not exceed the amount paid by you for using the Services giving rise to the cause of action or INR 100, whichever is lower.</li>
                            </ul>
                        </div>
                    </div>

                    {/* Section 10 */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#E1FF01]'>10. Force Majeure</h2>
                        <div className='ml-4'>
                            <p>We shall not be liable for any failure or delay in performance of obligations caused by events beyond our reasonable control, including but not limited to acts of God, natural disasters, war, strikes, labour disputes, government restrictions, or network failures.</p>
                        </div>
                    </div>

                    {/* Section 11 */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#E1FF01]'>11. Governing Law &amp; Jurisdiction</h2>
                        <div className='ml-4 space-y-3'>
                            <ul className='list-disc ml-6 space-y-3'>
                                <li>These Terms shall be governed by and construed in accordance with the laws of India.</li>
                                <li>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Lalitpur, Uttar Pradesh, India.</li>
                            </ul>
                        </div>
                    </div>

                    {/* Refunds Section */}
                    <div>
                        <h2 className='text-xl font-bold mb-4 text-[#FD3EB5]'>Refunds</h2>
                        <div className='ml-4 space-y-3'>
                            <ul className='list-disc ml-6 space-y-3'>
                                <li>We will notify you once we&apos;ve received and inspected your return and let you know if the refund has been approved or not.</li>
                                <li>If approved, the refund will be automatically processed to your original payment method within 10 business days.</li>
                                <li>Please note that it may take additional time for your bank or credit card company to process and post the refund.</li>
                                <li>If more than 15 business days have passed since your refund was approved, please contact us at hello@festbuzz.in or [insert phone number].</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            {/* Brand Logo Repetition Section */}
            <div className='flex w-full justify-center items-center flex-wrap mt-20 gap-8 mb-12'>
                <div className='flex justify-center items-center flex-wrap gap-1'>
                    <Image src={whiteDiamond} className='object-cover md:h-8 md:w-8 h-5 w-5' alt='' />
                    <div className='font-clash md:text-4xl text-2xl text-[#E1FF01] font-[600] uppercase'>FEST</div>
                    <div className='font-clash md:text-4xl text-2xl text-[#FD3EB5] font-[600] uppercase'>BUZZ</div>
                </div>
                <div className='flex justify-center items-center flex-wrap gap-1'>
                    <Image src={whiteDiamond} className='object-cover md:h-8 md:w-8 h-5 w-5' alt='' />
                    <div className='font-clash md:text-4xl text-2xl text-[#E1FF01] font-[600] uppercase'>FEST</div>
                    <div className='font-clash md:text-4xl text-2xl text-[#FD3EB5] font-[600] uppercase'>BUZZ</div>
                </div>
                <div className='hidden md:flex justify-center items-center flex-wrap gap-1'>
                    <Image src={whiteDiamond} className='object-cover md:h-8 md:w-8 h-5 w-5' alt='' />
                    <div className='font-clash md:text-4xl text-2xl text-[#E1FF01] font-[600] uppercase'>FEST</div>
                    <div className='font-clash md:text-4xl text-2xl text-[#FD3EB5] font-[600] uppercase'>BUZZ</div>
                </div>
                <div className='hidden md:flex justify-center items-center flex-wrap gap-1'>
                    <Image src={whiteDiamond} className='object-cover md:h-8 md:w-8 h-5 w-5' alt='' />
                    <div className='font-clash md:text-4xl text-2xl text-[#E1FF01] font-[600] uppercase'>FEST</div>
                    <div className='font-clash md:text-4xl text-2xl text-[#FD3EB5] font-[600] uppercase'>BUZZ</div>
                </div>
                <div className='hidden md:flex justify-center items-center flex-wrap gap-1'>
                    <Image src={whiteDiamond} className='object-cover md:h-8 md:w-8 h-5 w-5' alt='' />
                    <div className='font-clash md:text-4xl text-2xl text-[#E1FF01] font-[600] uppercase'>FEST</div>
                    <div className='font-clash md:text-4xl text-2xl text-[#FD3EB5] font-[600] uppercase'>BUZZ</div>
                </div>
            </div>

            <CallToAction />
        </div>
    )
}

export default page